name: BlockShufflePlugin
version: '${project.version}'
main: me.exaraton.citioxs.blockshuffleplugin.BlockShufflePlugin
api-version: 1.18
authors: [ citioxs ]
description: Custom versus plugin with goal to obtain certain block in given amount of time
commands:
  runBS:
    description: runs BlockShuffle with default settigs
    usage: /<command>
  FBP_plugin_commands:
    description: shows available commands to player
    usage: /<command>
